apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: database-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: /custom-tools/ksops
files:
  - secret-cnpg.enc.yaml
  - secret-keycloak-db.enc.yaml
