apiVersion: v1
kind: Secret
metadata:
    name: cnpg-platform-owner
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:jY82leQLolomS4MQ72s=,iv:GV+XfAoleSI8mqvCDTBlnxLmW6TXMysu+M/tZyEeSBA=,tag:xr87YBazrObvoiGvtqsxMQ==,type:str]
    password: ENC[AES256_GCM,data:CFrf9AaXdx+HmRk6Dtt8KrXBHP0quFIoA6xcBCcjWkdkyvA=,iv:t6j6E2dWR5GYUUhLzi0aQ7Diggwq7Nts+pbVdMuYUVc=,tag:n1xJYMyG2tf11ckcrdotVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQ0hKNjJQWjk2U29yUnJl
            OVNETXNtRGlmQldCQ1BRMHY0Q1QxSTJ5bzA4Cm9KNEtUTjRQMktkcXl5WGYwUnBw
            bkJDNjREYUxGak5tUVYvcXZIMU9RdGMKLS0tIFptNW1SSjRRcFA5WVl6NXpPb3lM
            Rksxc1VSc1lpSDVTRGlpTkZLb2ZIODAKtwvsn9JB7U7rnhGvsnc6Uo3+EILnivv1
            q5Re1f2dzLFVlxhAvkseTyLz2JuHDH200QMxcIw2ilIJuC+gWZB1xg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f3etpqekrkgzvfa99ezwv8alwc4jfz29ja440hkyl7xeprk3ge9szujunz
    encrypted_regex: ^(data|stringData|crt|key|secret|secretboxEncryptionSecret|id|token)$
    lastmodified: "2026-08-14T18:15:44Z"
    mac: ENC[AES256_GCM,data:t8pizAUqHWc1cHhn4+t4fRTjjajlre+glS9ZUMdpA2S3AtVgGiiIrwRQntssEK1dZrke6gck4+NKOxsLJh/9yQvvOmv0/WtrIzAw3r4bqFm/fJAYuaL6L1MYoxNDmVx893OVPx8y9SgLZzSUEe9r2W+K9Ajd0a3yQbP/jolPdPg=,iv:yVt5+Cip79oqz9FddYSzNl67fjdCJX3WQAPN5wgc2Ms=,tag:IoY1iVoaQxYH1jxrifS3dQ==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-backup-credentials
    namespace: database
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:qtfTZ4I5rsXcVDcu84yFFgRABAdFinGPmbPLkEOj5XWt,iv:OORsM9IzqMs6PT90ea34JwdncoNC0uA6H/Fh8LWYHeQ=,tag:fj0JZrWFSlanDQSsZquqWg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:WFPmOmfJC2eDwHYltBaS+xi1N6p7BQNiLZVeEY3RM9PH,iv:kPuOZJ7hclGEWXrKhv1b81AhgjNyvzs+xgLrUsJDSrM=,tag:3K7T6g1J5n1lmZEKSmB9Iw==,type:str]
    REGION: ENC[AES256_GCM,data:+TEVn+XC+38c,iv:wMETq/8qiYuTGHnN19qS2d26/+30hjGLJOechLRuMlU=,tag:YyHX8+Auxh6hLcXoyluaVQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQ0hKNjJQWjk2U29yUnJl
            OVNETXNtRGlmQldCQ1BRMHY0Q1QxSTJ5bzA4Cm9KNEtUTjRQMktkcXl5WGYwUnBw
            bkJDNjREYUxGak5tUVYvcXZIMU9RdGMKLS0tIFptNW1SSjRRcFA5WVl6NXpPb3lM
            Rksxc1VSc1lpSDVTRGlpTkZLb2ZIODAKtwvsn9JB7U7rnhGvsnc6Uo3+EILnivv1
            q5Re1f2dzLFVlxhAvkseTyLz2JuHDH200QMxcIw2ilIJuC+gWZB1xg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f3etpqekrkgzvfa99ezwv8alwc4jfz29ja440hkyl7xeprk3ge9szujunz
    encrypted_regex: ^(data|stringData|crt|key|secret|secretboxEncryptionSecret|id|token)$
    lastmodified: "2026-08-14T18:15:44Z"
    mac: ENC[AES256_GCM,data:t8pizAUqHWc1cHhn4+t4fRTjjajlre+glS9ZUMdpA2S3AtVgGiiIrwRQntssEK1dZrke6gck4+NKOxsLJh/9yQvvOmv0/WtrIzAw3r4bqFm/fJAYuaL6L1MYoxNDmVx893OVPx8y9SgLZzSUEe9r2W+K9Ajd0a3yQbP/jolPdPg=,iv:yVt5+Cip79oqz9FddYSzNl67fjdCJX3WQAPN5wgc2Ms=,tag:IoY1iVoaQxYH1jxrifS3dQ==,type:str]
    version: 3.13.1
