creation_rules:
  - path_regex: \.yaml$
    encrypted_regex: ^(data|stringData|crt|key|secret|secretboxEncryptionSecret|id|token)$
    key_groups:
      - age:
          - "age1f3etpqekrkgzvfa99ezwv8alwc4jfz29ja440hkyl7xeprk3ge9szujunz"
