creation_rules:
  - path_regex: \.yaml$
    encrypted_regex: ^(data|stringData|crt|key|secret|secretboxEncryptionSecret|id|token)$
    key_groups:
      - age:
          - "age1r9dj05axagksw2xxryta4w4q6xqqtahdqsfrqxzrvtnjcjxd0fxqueduun"
