machine:
  install:
    disk: /dev/nvme0n1
    wipe: true
  certSANs:
    - 192.168.178.100
    - 192.168.178.101
  network:
    interfaces:
      - interface: eth0    
        dhcp: false            
        addresses:
          - 192.168.178.101/24   
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.178.1  
        vip:
          ip: 192.168.178.100
cluster:
  allowSchedulingOnControlPlanes: true
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: basepc