apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

# Zusätzliche, handgeschriebene Resources (Dashboard-Absicherung)
resources:
  - middleware-basic-auth.yaml
  - ingressroute-dashboard.yaml

# ksops entschlüsselt secret-traefik-auth.enc.yaml zur Build-Zeit
# und generiert daraus das Klartext-Secret "traefik-auth"
generators:
  - ksops-generator.yaml

# Traefik wird über den offiziellen Helm-Chart eingebunden und
# via Kustomize "inflated" (letzte Anpassungen über patches möglich).
helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: "41.2.0" # Version fixieren! Prüfen: helm search repo traefik/traefik --versions
    releaseName: traefik
    namespace: traefik
    valuesFile: helm-values.yaml
    includeCRDs: true # liefert IngressRoute/Middleware/... CRDs gleich mit