apiVersion: v1
data:
    users: ENC[AES256_GCM,data:tjA/SaAbbyd4TZwMFF3wTn/aO/pKX5OZgThJf7YKe0pTIyM4l/lVCCrorIU0dx8Ho7WqCjqQVi6d97W4x0ZJ8swDeirqkezzLo3ZJZkCJqgy8Z40uxFi6A==,iv:izdvcMTZGUrGqH/ekJIsYELM7u9GuWp/693qINi6pLI=,tag:6RIn7mJtZWd+2p9a7qVI2w==,type:str]
kind: Secret
metadata:
    name: traefik-auth
    namespace: traefik
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMFlGem9ubkNtYU5UVHlo
            OENtNVorRzB3eEdhdUt5bm92eisvZk05OTJvCitQdm9GbHoxbFVsak5Sc0dtSW1S
            RzZDUWFTNElKZzZvS3c3N3VqR0Z6a1EKLS0tIFlZcGdrOWJqMVpMY2ZtWTFxMzRE
            V1hHMGcvNEsxWm10WVJRWW5GSldIT1kKBccawjEEU3PupKN13Oz6Bhw78CnFgVLV
            w53g73XQ/wM7VjumwXeQzkRec0/lt5qjorVXP3uFFGzSegQsjhqDFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ztxdvvz40vgyyskexhl26plh37rn8axeahsfh49tqkwvy8vv7f4st8kcw5
    encrypted_regex: ^(data|stringData|crt|key|secret|secretboxEncryptionSecret|id|token)$
    lastmodified: "2026-08-26T21:38:57Z"
    mac: ENC[AES256_GCM,data:4ygjya0txA+Klcdbwsbg5AYEzcf2EQkVpOAc1DtFf/xBE86OnXubkSZ0kS24vApB2X6ezieTTO19O2/cKqyPVB0zfT9Y5chdqJTez28largnBielrxZJ7VH96Tt95QD7auM1y3UBc7tITtKhP2iXOUGTUtGn+xD49W60GtRHDa0=,iv:GDW5TuWMeYllfgTsLniUsj6KY+Jcur3cMKTSPDw234Q=,tag:JO3MskcFGFdYUFHHg5Tb/g==,type:str]
    version: 3.13.3
