apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: homelab-internal-ca
  secretName: internal-ca-secret
  duration: 87600h   # 10 Jahre
  renewBefore: 720h  # 30 Tage
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-bootstrap
    kind: ClusterIssuer