apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: keycloak-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: /custom-tools/ksops
files:
  - secret-keycloak.enc.yaml
