apiVersion: v1
kind: Service
metadata:
  name: adguard-service
  namespace: network
spec:
  selector:
    app: adguard
  ports:
    - name: web
      protocol: TCP
      port: 3000
      targetPort: web-alt

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: adguard
  namespace: network
  labels:
    app: adguard
spec:
  selector:
    matchLabels:
      app: adguard
  serviceName: "adguard"
  replicas: 1
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: adguard
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: adguard
        image: adguard/adguardhome:v0.107.76
        ports:
        - containerPort: 53 
          name: dns-udp  
          protocol: UDP
        - containerPort: 53 
          name: dns-tcp 
          protocol: TCP
        - containerPort: 67 
          name: dhcp-srv  
          protocol: UDP
        - containerPort: 68 
          name: dhcp-cli 
          protocol: UDP
        - containerPort: 80 
          name: web
          protocol: TCP
        - containerPort: 443 
          name: web-https-tcp  
          protocol: TCP
        - containerPort: 443 
          name: web-https-udp  
          protocol: UDP
        - containerPort: 784 
          name: dns-quic
          protocol: UDP
        - containerPort: 853 
          name: dns-tls
          protocol: UDP
        - containerPort: 3000 
          name: web-alt
          protocol: TCP
        - containerPort: 5443 
          name: dnscrypt-udp  
          protocol: UDP
        - containerPort: 5443 
          name: dnscrypt-tcp  
          protocol: TCP
        - containerPort: 8853 
          name: dns-quic-2
          protocol: UDP
        volumeMounts:
        - name: adguard-work
          mountPath: /opt/adguardhome/work
        - name: adguard-conf
          mountPath: /opt/adguardhome/conf
      volumes:
      - name: adguard-conf
        persistentVolumeClaim:
          claimName: adguard-conf-pvc
      - name: adguard-work
        persistentVolumeClaim:
          claimName: adguard-work-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-conf-pv
spec:
  capacity:
    storage: 50Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual  
  hostPath:
    path: /var/adguard/conf
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - basepc 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-conf-pvc
  namespace: network
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-work-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /var/var/adguard/work
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - basepc 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-work-pvc
  namespace: network
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi