apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Kustomize injiziert diesen Namespace automatisch in alle Ressourcen (außer Cluster-weiten Objekten wie PVs)
namespace: network

# Fügt allen Ressourcen und Selektoren automatisch das Label 'app: adguard' hinzu
commonLabels:
  app: adguard

resources:
  - namespace.yaml
  - service.yaml
  - statefulset.yaml
  - pvcs.yaml

generators:
  - secret.enc.yaml