apiVersion: v1
data:
    password: ENC[AES256_GCM,data:rDMYwo2GDFM=,iv:Bd0PW06C5iO2dfnITZz8ByETL4NiQYqRRLnAzDmZt6Y=,tag:LPKx0ysoqUdfNvRmm+bgMg==,type:str]
    username: ENC[AES256_GCM,data:dHnDQejc7p8=,iv:CGheGzI3SfrJkVYsHVQ0jgka2j9sdtqqH0wWkZ2nhqA=,tag:N2TqKeCferWSbphTr1vvBA==,type:str]
kind: Secret
metadata:
    name: adguard-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UGRIL0FwcTk0YWxiWmRz
            NGpBMVYxdXJWNzY4NzhtQkthK3hGbzQ0alhnCmJ6VVZ2YVUvU0dUb0ZxcWcxWi90
            QlRKWlYrYjlaVlpiZ3RZT0V5ZFoyUUEKLS0tIGxiWjkvV2o2Ri9LbHdUOXpBVDZa
            RFJWbTc4bUpaODU4bW9telQzdHc4TmsKNvmc9O0Azp4q0nZFaaFO9qH5J/OhdgO/
            74ouBC6ESPKIAsnkyDywVXdIbVpKaV71JduSScy2QdDf5AA6pBHieA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f3etpqekrkgzvfa99ezwv8alwc4jfz29ja440hkyl7xeprk3ge9szujunz
    encrypted_regex: ^(data|stringData|crt|key|secret|secretboxEncryptionSecret|id|token)$
    lastmodified: "2026-06-16T15:31:56Z"
    mac: ENC[AES256_GCM,data:aihW8NtwnLieDUj0MjbUpbFD6i+YZNTip5pwWh+USyNiW7enfCKGKAE8fNb+PWXMbY24/2vmQOyhp9osOSQ7px0iI9vkvhwAkRihTDB/xIGw/iCG253DPcNcp3NvfZ07fp2Prq/KQh185LJQyVATia2QvgHfIyxIY/Sn0UY/8Kw=,iv:FgQR5/8hSE6soAKNlu6RG9PqZGLb7aJ96YFgLx6dzko=,tag:qRf+U1EXklYEdikLCHE8iQ==,type:str]
    version: 3.13.1
