apiVersion: v1
data:
    password: ENC[AES256_GCM,data:kI6nYQ==,iv:LnJxtrlYUj1W/cXm74atCXRJVI5wfutwfyhnX5AyV3A=,tag:9TBis2pd4+ug6PBDr33FxQ==,type:str]
    username: ENC[AES256_GCM,data:hdCePY2GlDs=,iv:uEqBSWibK7cxCH0VDdXiQu30OrtP6ytJs9LfAcSFJ0k=,tag:HBBZe35pxywG5xz+/jZ42A==,type:str]
kind: Secret
metadata:
    name: adguard-secret
sops:
    age:
        - recipient: age1r9dj05axagksw2xxryta4w4q6xqqtahdqsfrqxzrvtnjcjxd0fxqueduun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSXdNODdEQ2w1RzZDaDla
            a1ZFN3ByWmJGU0hmSXJTWFhsTmtxMnE2dHdJCkFFdi9ZOWNwVVdvNDQ3RmNXNEQ0
            bUJ1YmY3RnU1NGpMdjFyckxzQ0xHTGMKLS0tIE5kNjZIMUhJNWM4ZHBCQVZCbWw3
            YmJBTXpyUHBIdk5Nb1hacXZwNkZ0Qk0K/q+BlHZQ0r1UfHaRcc7tT451epdviuNA
            Zbi2K6AdMiRwsCrhmBHh1rjq65YOMC6fbprQDTt3+mxThsAXTNks9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-06T10:19:21Z"
    mac: ENC[AES256_GCM,data:MZKZMRHw9RmUnlOjWLMDjDPsaU2ccTtmFfwBifcdQdEngjzTFCSVVW8OFH9UTybdJBcvV6hWIJKDF2NkJYdfnAVE0GviNOaSdh2C2XDDUNs8/5HedJSRb+PiXOw6ZoTZqkUPYOhY33giRQMoIhg1qt35pkqt79x5rzWJxToW/38=,iv:ttfUNowEiHnZFYBKBd4Tc8vqu7+HPq4aO99qvJ1/wVw=,tag:xz9YxtReiTqTnx/nFDYA7w==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|secret|secretboxEncryptionSecret|id|token)$
    version: 3.12.2
