apiVersion: v1
data:
    users: ENC[AES256_GCM,data:fliLnRClBxU9ettyE7i+IiuII0dgGWwOqVpG4ryAaWC/HXbDv+q3DaDhHz09iZ21xevj8Z5PKZ4FpXqVQT4jmjel+sQuYloQKyvwNNuqb+T2gIIESuMGTg==,iv:KF+R4To/jZYnyhqFLZf0GsZEjMbFo9NpeY3uw+SVHRw=,tag:eMKsbn1z35Z0VlZXWy0lyg==,type:str]
kind: Secret
metadata:
    name: traefik-auth
    namespace: traefik
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyb1h2L0xvQmI1UDI4K3lz
            Y0dKdVVFRWZ3Sk1vUWc4RHgwSENBSHl5aUNFCkxhanZvMmdBaHI0d0s2dThjOEQ5
            K0JsTFlaODJRQ096VmNZdmVFS1NCc3cKLS0tIHRJMHpSZzV6bTBYOGdZYVRiNlB6
            Nit6RVZCUFhrSjhLQTdaa1BxY0hBd0UKfn5RVAErhajyYnYBadmdV5xLGMQ79ESj
            +0OiOWILsEL6xjim+lSjfY2hV4qTF+rUrIiD1a0R11orl2m6VwIXLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ztxdvvz40vgyyskexhl26plh37rn8axeahsfh49tqkwvy8vv7f4st8kcw5
    encrypted_regex: ^(data|stringData|crt|key|secret|secretboxEncryptionSecret|id|token)$
    lastmodified: "2026-08-26T20:46:35Z"
    mac: ENC[AES256_GCM,data:3V3ESaB/7AaBdekAmzpYWYtz5d+oHS0E6m4YmtUXGwgtNlPjw3sbf38T+NfjynZfBIDIbZGtFiwqmhTENbd7povdhLbt9cPFTzqTWjc67muElVwUwssvVigpKfAfA+MQdEROMVJCVtI2rJXRMV1a1r9WuGbchw0gPgLHzL8argA=,iv:7wyW1AgI2Xsgp9jn7PCLkIe9zIrwxk/kpPDBUnoaefY=,tag:aPDF9iaYejAAmD7F6tTPLA==,type:str]
    version: 3.13.3
