apiVersion: v1
kind: Secret
metadata:
    name: traefik-auth
    namespace: traefik
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:zVx+IGOAPYVorE281mj+xqoEHkijiDPBWDSckKJARkStw7Bl9WLnC+XlFXoEiqjA9ZHea4irEoYnAxtowRMGa/BXxg==,iv:zp8tkYvP9ybgpoqtqnc3338xhNAKSKsD0GNpuL0tOu8=,tag:glr+j+1nAcawGr0ckbCspg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYzZIeDBBRjJDTXJoNXkx
            d3FkSDRtZmxLT3lvVHdjUC8xaGNqSFJELzB3ClBBU2YwVUY0WHdwYjhYbFovQTlJ
            MjMzaDJiTHg3TXhtSXNhLytySTJHajQKLS0tIHJTYVBzTzEvQnBtekplR2t6dU1S
            RkczZE9pU3JxTFNad0xmZ0UwQXpqY0UKL71N2jOpPXBUpuRmnrd4YdA9UrReHDy4
            gDEasBcYi44nSCBwDKe9SgvAUEYe2aI/QaqYavNwricwq+sLcOOuSQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f3etpqekrkgzvfa99ezwv8alwc4jfz29ja440hkyl7xeprk3ge9szujunz
    encrypted_regex: ^(data|stringData|crt|key|secret|secretboxEncryptionSecret|id|token)$
    lastmodified: "2026-06-25T19:38:09Z"
    mac: ENC[AES256_GCM,data:kHWLmoTCLCBxjWUiXGbr4Li6XrXM7WzpbffK5xAnUHw8HWCm60tclnegX/3MtH7wz9IbUYLVhL8MlZW+smfsb1lwSLGGj4el2p2DRJoVrwW8284q1ProNQ1zBfg+JQOjUonydR0xOwLLOz1Eb0j9mMqAxu/CxZIThHCTBgkkhuQ=,iv:rRkRILyZCzhiRe8Fw4sQ6p7X9a0uLHUiEIGShvpI/gI=,tag:obB38fhwT/qKf9Vu5+Upxg==,type:str]
    version: 3.13.1
