apiVersion: v1
data:
    users: ENC[AES256_GCM,data:ScMn7Qe+rWsDjM42PtQsyvcDrdgm4IwU6+PkFBl0S8lD1CaIB3EgKGuC32sKRcLLUIuP8N4s30gM4WSnQ/rxNwrdMzY2MYVamlporjqr/E/ctgqEyoQTcQ==,iv:4UZnLE9PcaikOJLxkguA0q9Z7mRAFHgdUG41HPJi/Fw=,tag:3qQkN9wgpSl8W+N3TeLJ+Q==,type:str]
kind: Secret
metadata:
    name: traefik-auth
    namespace: traefik
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNc0tCYUUvSFhIbSticER1
            eEIzUi9EWlRpVGkyZGtwOGh0WGRpa3FqZmxrCkpwUEErVUZTS2xCT3NQSlR1c29m
            eHM4aytBSHQwelNlUkZibmw2UzJMOHMKLS0tIHFPU1k1UUxhQ3kxUEZmWFlaUENH
            eGk4MG1KcW05SkVQak5HYW5ydHZjeTAKyk6UFWUifO1P55FrAMxJR4b6TQofSYAi
            EmsdUFXknUrFqpwZcKOPY5j0g2SOhnDrm74nVqwIpdEPDJ1UdIIPIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pszj5xvk248evsdmj5epsz89nw7a2utuareefkwvg8x6rayvny5s2at4aj
    encrypted_regex: ^(data|stringData|crt|key|secret|secretboxEncryptionSecret|id|token)$
    lastmodified: "2026-08-19T19:28:33Z"
    mac: ENC[AES256_GCM,data:UFcQusLge+gugIzc4Z3hz1tA12ZbWawy6WidYnQxt37oPdTlSicWY9LrD0tEqNCmKsbogEjnil9TcWCC2tKA8rtysK8OX4/FJFGDkPcJmHXyxv5FES2QKToQDiQ3w/l53D4gVOP2h6O4FtH20dP8EsKbnK38IIWcZMLp9qFWFrA=,iv:TJVPt/C+FRtdFN+X0518kWxwiANDVGtFh5gNVSt+N3k=,tag:K1i6Pt1QunvN6apeBcQibA==,type:str]
    version: 3.13.1
