defaultSettings:
  createDefaultDiskLabeledNodes: false
  defaultReplicaCount: 2
  defaultDataLocality: best-effort
  replicaSoftAntiAffinity: true
  storageMinimalAvailablePercentage: 10
persistence:
  defaultClass: true
  defaultClassReplicaCount: 2
  reclaimPolicy: Retain          
longhornUI:
  replicas: 1
longhornManager:
  priorityClass: ""