apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - certificate-longhorn.yaml
  - ingressroute-longhorn.yaml
helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    version: 1.7.2
    releaseName: longhorn
    namespace: longhorn-system
    valuesFile: helm-values.yaml
patches:
  - target:
      kind: Job
      name: longhorn-pre-upgrade
    patch: |-
      - op: remove
        path: /metadata/annotations/helm.sh~1hook