apiVersion: v1
data:
    users: ENC[AES256_GCM,data:6nspm+eqh+xqHcrW+rVQ+tahJ+atlCO+bdGnNIsaVQmH8Qp5VJp2RiOCjXQcajqG/GbpMgVlFXUmxx92VeenJ1sfV6pJPVohGkRVs4jLvcEzEaH3Pvgc5w==,iv:EmBrx4+Wo4mRyLfKv43/RcaB/JzxtTbeg6RgUuSW1dM=,tag:NcDjVnvtkHJ1qBZNefkZdg==,type:str]
kind: Secret
metadata:
    name: longhorn-auth
    namespace: longhorn-system
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cjVJVWJWNUhHWnFKNlMz
            Ty94blNZeHZxR1lKZVgwak5EWCtQWno0a0ZnCldoRFhoYkZFTkVxTFoydk15Wlg1
            UzROWElQdzU0TC91ekc4Uy9QYUNQcFkKLS0tIGtweVBxd1VLTS9jalNoR3NtVUZJ
            U1l0S0VjK2ZNYzZCcVR5TXhYUmxqdGcKyzp2I3mO8ouQ5AkPrMmB1Jfac999R7ZV
            9c0OIykyO9bV5qO92sfdiDlLi1P0kAykTnpV963lHakH8jQabrZPvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ztxdvvz40vgyyskexhl26plh37rn8axeahsfh49tqkwvy8vv7f4st8kcw5
    encrypted_regex: ^(data|stringData|crt|key|secret|secretboxEncryptionSecret|id|token)$
    lastmodified: "2026-08-26T20:46:43Z"
    mac: ENC[AES256_GCM,data:ScjF5NNNyqvmGyfJfe3r5jz7ZTF0PV0v7i3ojfnx7/JkqqwyBaN2ZyiY9ncX+XIHYXQVc2FxnuHlaeyj79eA/g3lLDbD/YLN73kni5ufZs5QEXA6k8YAQd1Aj6o8IqdXOHGJW7CDecyHXbsgCTU0nuOavpo7SoXCItZV6Wjpviw=,iv:Im5BN1Bl+ZQu3mGhhxEzgvDvUebIbRuBG9AdkjRE/4A=,tag:lbZI+Ln0eDHqO4oD2WI52g==,type:str]
    version: 3.13.3
