apiVersion: v1
data:
    users: ENC[AES256_GCM,data:XPcCMdPxCqXBar2vbcHX7J7vToqAq9tPx8o8elU8qH6mvZY/W4UBFAtnABznzD7uKXPRdsrjjIufIhr1FdQsgfWKgmMhEW7Qp7yYEpt2kgQcYf33yoIA2A==,iv:bLtXw9e9iY1L0RUp3geZch41chyGZ8gP7h1QBeu7ILo=,tag:nFnFVwn+0BZj4rr2XZf2Dw==,type:str]
kind: Secret
metadata:
    name: longhorn-auth
    namespace: longhorn-system
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OXhGM0V1Q1FUUjFldmJa
            SVV6NFBmL0J2VHVyak5QLzZlQVFFb1pvdXcwCkJlUWFlMExtYUREblJRMUxzWEp4
            aEkwdzJ3UitYdkJPT25uTWkyek8zRVUKLS0tIFczNTJXZWQ4Tnl0Y0hTWmVUWjNO
            eVZudUJtb0NOVlNEQmJEdXg3VDFyK2MKHExzlIPeoRpI6n5rSgGqJnjAMaCqQGtm
            pby7/iAUjyWFh3+XqMJuUtesLwv0Vsi6bn8UNKGZ2Ted/Ycvz/VLfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pszj5xvk248evsdmj5epsz89nw7a2utuareefkwvg8x6rayvny5s2at4aj
    encrypted_regex: ^(data|stringData|crt|key|secret|secretboxEncryptionSecret|id|token)$
    lastmodified: "2026-08-24T20:52:13Z"
    mac: ENC[AES256_GCM,data:7vvI7+2fstBlJ5Onuo8c0JkcVATqrmfaXBd5bWVq2qa2lQWTwHd/j/pFSaiQ/Uc/ThBzquBnoqQX5cpPPHachQ4rCKZBXv9/kQGbtBaOh+tsvTtFIMsJxBHIxH0JCttWUk7fG3meBWo07x7NcQBXdqhPAg/iUS/RzzpsbSNPpe8=,iv:xldXuEjGmnI09EzJzA3QlANF6cpsLXBgvH9tcYWhDTI=,tag:v7eXlSx21RUVtcXFjJpe3w==,type:str]
    version: 3.13.1
