apiVersion: v1
data:
    users: ENC[AES256_GCM,data:3yQ4J0GsJoqdcIFA1c11oIUJ/x2NcTlcckRrd//pIix5Z4cbZHY5qy4/6ad/9PKmj56zxnHqF2pNqjW5xdShwKDsduqBR/6R0041HQoTaZWKLzfgDtFOqg==,iv:PM4qo5v2lplOyZ5QBbMGBEDBXEQypf4iukITwE/sgx8=,tag:0pqFuLhlKRZ7PMFhKosnCA==,type:str]
kind: Secret
metadata:
    name: longhorn-auth
    namespace: longhorn-system
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SnF0WDViZ3ZERit6Y09p
            RGd2ZVFJbTJMbUNxcGEwSkVXNyszZlBoWWtvCkRhVDBuYVpWQnRnZ0FjSjZXU2lz
            K29aNzQ1OXNTOW1SeHc4d1gxdFA0MGcKLS0tIEtnSThHekpiMGtZZXJ6RnVLeTBj
            SDE0UnVWazNkSmVrQXlXNzIrOWRTcFkKZv5hY5Y3rXIUZPFCd2hA5A6tVwZGnke2
            vT8CqzeXyGhwHhaehlbz+myd7GWF4oxDfcUluc95FI7Ex0zzzk0mWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ztxdvvz40vgyyskexhl26plh37rn8axeahsfh49tqkwvy8vv7f4st8kcw5
    encrypted_regex: ^(data|stringData|crt|key|secret|secretboxEncryptionSecret|id|token)$
    lastmodified: "2026-08-26T21:36:43Z"
    mac: ENC[AES256_GCM,data:/onCmmxYdp/OpvpWbg/ZcyrXFxFkOLqAACk3Kc48CpjTN6NyxcOMVylI+1TG/S7jIDouiAyGDrxQoV3K43U0PflMIsV11l735XmMdYiQ8wlKsTtle9M54UbtIc2lmjO9q+VsFNiiSMl8Q7yerzfdnf31oUYB97v3+xpGet4aAzw=,iv:ifi3qVk5w2qnxD26RxsSOrtR03iH5+aBlhBEWCr3WFE=,tag:yrp8GKKnIAQQOCEAmrxq4g==,type:str]
    version: 3.13.3
