apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      volumes:
        - name: custom-tools
          emptyDir: {}
        - name: sops-age
          secret:
            secretName: sops-age
      initContainers:
        - name: install-ksops
          image: viaductoss/ksops:v4.5.1
          command: ["/usr/local/bin/ksops", "install", "/custom-tools/viaduct.ai/v1/ksops"]
          volumeMounts:
            - name: custom-tools
              mountPath: /custom-tools
      containers:
        - name: argocd-repo-server
          env:
            - name: SOPS_AGE_KEY_FILE
              value: /home/argocd/sops-age/keys.txt
            - name: XDG_CONFIG_HOME
              value: /home/argocd/.config
            - name: KUSTOMIZE_PLUGIN_HOME
              value: /home/argocd/.config/kustomize/plugin
            - name: KUSTOMIZE_ENABLE_ALPHA_PLUGINS
              value: "true"
          volumeMounts:
            - name: custom-tools
              mountPath: /home/argocd/.config/kustomize/plugin
            - name: sops-age
              mountPath: /home/argocd/sops-age
              readOnly: true