apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-barman-cloud
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/cloudnative-pg/plugin-barman-cloud.git
    path: .
    targetRevision: v0.13.0
    directory:
      include: manifest.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
