apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://github.com/Bean900/homelab-infra.git'
    path: cluster
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true