apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: network

resources:
- namespace.yaml
- service.yaml
- statefulset.yaml
- pvcs.yaml

generators:
- secret-generator.yaml     

labels:
- includeSelectors: true
  pairs:
    app: adguard