apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-conf     # Namen an eure bestehende Datei anpassen
  namespace: adguard
  labels:
    recurring-job-group.longhorn.io/adguard: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-work
  namespace: adguard
  labels:
    recurring-job-group.longhorn.io/adguard: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi