apiVersion: v1
kind: Secret
metadata:
    name: adguard-secret
    namespace: adguard
type: Opaque
stringData:
    AdGuardHome.yaml: ENC[AES256_GCM,data:i6gtRjxDU7XLLOwOXtuEGxqmFu7XzVi6X+UTsAONt/tsVKRTWDEn0A/frhvL42gNY0FvymZOxvhL4WqhX7czIFzUsXIhKkLr/iPcTQ/2dSbdD/RkxAfsQrxXqTYtuTYtZlNWRbmFRAlAvZM3AlBksNbB0ZjZ5F6sSRNDwQTfjWTpB2imOTgrsH+9ONTwD64GFH64RP7JLnMrTpH2VOABMgn8VMmfwOkPWDzbtlM5Kga+lnghb53y318OaiTj5LjpV+XBi7SEgjJ2vwzNiEQ1OYuwWGWSN0F3C9xp256+sNS2KYR/fXZqNoN56wdYfYn6OcBTu+vnsqiaXwdvAkZ8EK7/3zg2a//uO1AKDh+PNfSQVfS1/HR1ITYEYhTgZUIOn3oEKLgPYPlg6uKUU4dkp58fvQfAVeOmuFADjYg/Zpqs6KulhhXt8+BxciIXm6Sq5JYZedvLgqjnW58qjeB2Ide7Yu/2c1aTBOnWL7ccAquSfMdgZjftsxX1gwfXZFpffiJcmuFe3JJvXWd5biUhSYBH9QRiwzqAm4RvRFNT6i23eLjwB0zygQZH2GgNcWgk8MZxwmLzUUUtVcdx0C8X/cvCprnGyGk/KijSa5899jhtzdhIWJL84JDLUAYkAzPk5L6nBSVSsoCfzDIe3tReGLflmvSevUdklnUXF7Q/f6XvQydC3S5PW7tNubD2LD7gQVZ0UrsnvNHdctJ46qLA2aK69eFuZgS33Fe1b4riiRlowCG/u1AbRHM+INSr7xDltRESB8tmQ90NCUt4KgS9+u+rS24XXOXLD+k3yqrwi3kuXl59GdO4b7NAoGQVdPwzUAI=,iv:TrMGQAfCggaUIF443iD21pW97HowsmwA9fVvKeCJaJ8=,tag:BfJFulYeJViMehf2rT6L8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RWhSWVJwTVpWY3RJQUFM
            UHE5SXhTR1JuYkd5UE05TzVSRzNxWUU1eUNrCm1TOGVQVm9Ca1NjK1ZuZ3IwNSt2
            UkdXbkxTMlBHUlpUc3ZrbExKQmhHd3cKLS0tIFc3TG5QUysrSGdrZUJmQlQ1aUtB
            NDZTS2ZMRXc1b2ZZY2FhZGkwdUlGYWsKx2gelqo0AB/j1iuCM8Ri/ts27kbOdS66
            FN/ugOW8ZzO5OguijaVejme1sAYsnhzc45ow+orT+LFgNj3M7NntkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ztxdvvz40vgyyskexhl26plh37rn8axeahsfh49tqkwvy8vv7f4st8kcw5
    encrypted_regex: ^(data|stringData|crt|key|secret|secretboxEncryptionSecret|id|token)$
    lastmodified: "2026-08-27T22:31:05Z"
    mac: ENC[AES256_GCM,data:JhX/lbBAJDIiqLwEDLuFm0nTI5cMAwkPNx17O/sggJXdL+P51R+xyRvWenW56+mn/2wJX0a6gBQ+QA6KxG7g8RidzaI1LMJvCwFGtJxYehCpjtRYICbkDdCXbwP/c4D33phD4zu4y1FdYPe1Ke2SY4WHaOkzbV0rHD9/j1lHgFA=,iv:1RJsr2gmgmIbOU9m90dj8gOexYL5Ne9lccHv9rkcimQ=,tag:jGugQPhKnTSas7m6IdFgPA==,type:str]
    version: 3.13.3
