apiVersion: v1
kind: Secret
metadata:
    name: adguard-secret
    namespace: adguard
type: Opaque
stringData:
    AdGuardHome.yaml: ENC[AES256_GCM,data:FTWZWkB41XXbBg4PFYa+A7YlHzQD1pQken3OU2FKKwtc/2ltaGOGK7CC8HT2VJTC7vlrPpjNZZAyv1nTOpAawSKhDFXUaBtdcdhd409Le4mVDeBw4EesdLZzyBvhZY4JZNgJg6QRgRuPouXyul2KJfVJLHhHSvRRGvHIKF4nloMS22o82rb1Tr489vYDm7VK9A9b8DjpqgGZudPgNivPZax4m/AMe/7gIZw8YF/d3mrZ5RoDdqzGRwQBULi8ZWl/BfMXUHDSs20XC8/xyWII5bRGrF68jAXx8xIKnzA53FQayR7CXmtnUms88afP6wd0qLYPcV3eZDPannJJZ28vBY+VjDwrXeT19pmmJGjdzriG6s3nG9hBZqwBx9OpBLlzBSp3uQ/4IopPrC/wBms11wuhHYsc8NQyZYV+5iFOFhP0fI8ZprcTYL913caSx9LOHkYSyHyEn39YLz65LpbUnHix8zS5m/7jgA2pcBRJ742aA51S8CoXlSgh29iAW+p9PRnjd5bLrKDLUo4P7oVdqu2BZJJW9XCWrrcoRtwjp3Ga9bXCTMdRv6/x18jQGSjIJMSYU6L5TmCwPlXhS4NonWSk3NyumweZ7jjwoxCJISXKX2spqbqj3umP7eeNf6LZ4chs/iiUEw8dGDm63zo+QqI5rn9LsVCzZUI6CwQR4K1zkVGLSIRoS2qHM+jwYLzaHUOueAINVPz4vJavUWEhhB8nbY82fqyQmc2gIlf1kFPHtwaXi+oiXQibDpzQpTHViyh2NvpfItSoU1j0ma+1VrXpPlSUctmEkCwFUiynIVOTmEdwXoFmT8nQAZrOybCpkUI=,iv:iBrjzO6z8KUQjt6q/TqEw4Rg5rtPglIkRSRUUgQP6Hk=,tag:DMOO6WuIkLqwawDnhs+dFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUUpBR0U4YlMrZWUwMjRR
            M2dLQisyVWErb091enRCbE1PKys5eTlNRW44CnR3dWVlWHMrQXR1TURKdWVqTFBP
            c0hpV0w1UEo2QjNNc3g1citCWXBlajAKLS0tIEM4MzZ6WDNSU1FEOW1KeTNFMHhX
            UHN4L2FXM1FXeFhJZUFEUVo5dzlvTkUKQH9gtNKLqwW80Mp9glqH+M3kJidH2bM5
            lVXBRVXgOcQ+DQrhFE5k3/TIVy1BT+8P3KRKKGLosMrOvDn4I9hBUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ztxdvvz40vgyyskexhl26plh37rn8axeahsfh49tqkwvy8vv7f4st8kcw5
    encrypted_regex: ^(data|stringData|crt|key|secret|secretboxEncryptionSecret|id|token)$
    lastmodified: "2026-09-26T13:40:38Z"
    mac: ENC[AES256_GCM,data:FUMcYODEWklNPF5p7yGtDQpCEJ/rFo1dP9WL6mJTJYsTME7hTRawTbqJyl8NM7C8oG+Bcnf6QdnPG287AVzIX8O3rEBFcDze0t6nKhF82wnhQjxgkeyN79mG6LH1fGNslFDjZu2CIGykT8DWkugkscajJVi5A3RN7Kc6fQ6d/yE=,iv:GTvi/tcuufkGTAPDxsnTdsIYDBHed1ASOlnvJ692NdA=,tag:a7j86uG84dAGh23+SYEvKw==,type:str]
    version: 3.13.3
