apiVersion: v1
data:
    users: ENC[AES256_GCM,data:h4YUnsXatWsDhNd4Fa0duJpRCFe7400/GyE7+OkJVx152OJMqTEwRoeG/T9T3PEAcCZ/TSvlff6nY9Mu7AfqLc6i9Ts2RPRcrOgTaD/QeBn9WjCd4e/8Bg==,iv:qQ033NZ1bQQtFi2OkaH/C/v1NVoqf7pUUulB70lwQbw=,tag:13sTsvvVZCqTJLJX9vNUDQ==,type:str]
kind: Secret
metadata:
    name: traefik-auth
    namespace: traefik
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnKzBXZSt1OVVjVFQxVzJE
            anhkUWRmVkV0K3IwZHBMK2luU0w3MWJPb0FFCmVtT1N0c29xMFFjOE51a04yenBp
            Mnk1MzZHUTcwMDM1cWoyamhtYmdyM1EKLS0tIGFhLysvb0R4QWdRRFJrQktrOURI
            b0VmOFpQUzEzQ2N0MW91Lys3YS9RaVUKg4J73LciyLdk7sI4SqAA8XsWD7prFZLA
            uE//kI+ZwCrvyHu6jZNkDDurh9/s2/XwFo/iJcfHSpNJ2UPLJ8/3yA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pszj5xvk248evsdmj5epsz89nw7a2utuareefkwvg8x6rayvny5s2at4aj
    encrypted_regex: ^(data|stringData|crt|key|secret|secretboxEncryptionSecret|id|token)$
    lastmodified: "2026-08-18T21:07:36Z"
    mac: ENC[AES256_GCM,data:H51CPdDdbwuHpedOnPnGE7UWTjdJRIFc6/BWNzIJM7sqA66amKF2SXb9K8ceI7wz7V8wRED2s4PlgnA/c7pWzvRuKwfV0j/QvrknmjkRN7Wf/DwZJ0gH/PclhimUzeTaav+bn1qne11wDP1aG3kcM3d0xFiRaRGYdI4I9rUfLgY=,iv:EFHvwytpTxnEFnalql8A4/KOiQSQDelpARMf1eeG5Lk=,tag:PYeNeP5P3cLWM7n5mtebqw==,type:str]
    version: 3.13.1
